FROM python:3.8-slim-buster

WORKDIR /app


COPY /API/DataEngine/App  /app/API/DataEngine/
#ADD titanic /app/

WORKDIR /app/API/DataEngine
RUN pip3 install -r requirements.txt

#CMD ["python3 App.py"]
