version: "3.9"

services:
  Titanic_DE_API:
    container_name: Titanic_DE_API
    image: titanic/api-de
    build: 
      context: ./API/DataEngine/
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
  Titanic_PE_API:
    container_name: Titanic_PE_API
    image: titanic/api-pe
    build: 
      context: ./API/PredictionEngine/
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
